#!/bin/bash

VIMFOLDER=~/.vim
COLORSCHEME_FILE=jay.vim

# Try to create a folder and return 0/1
ensuredir () {
    if [ ! -d $1 ]; then
        mkdir -p $1;
        cecho green "OK:"
        echo " create dir $1"
    else
        cecho green "OK:"
        echo " dir $1 already exists. Skipped."
    fi
    if [ ! -d $1 ]; then
        cecho red "ERROR:" 
        echo " Can´t create $1";
        echo
        return 0;
    fi
    echo
    return 1;
}

echo


if [ "$(readlink ~/.vimrc)" == "$FILESROOT/vimrc" ]; then
    cecho green "OK:"
    echo " ~/.vimrc -> $FILESROOT/vimrc"
else
    if [ -f ~/.vimrc ]; then
        cecho yellow "WARNING:"
        echo " ~/.vimrc already exists.";
        echo "you can link later using the command"
        cecho white "ln -s \$FILESROOT/$COLORSCHEME_FILE ~/.vim/colors/$COLORSCHEME_FILE\n"
        echo "or running this script again"
    else
        echo "Linking $FILESROOT/vimrc";
        ln -s $FILESROOT/vimrc ~/.vimrc;
        if [ -f ~/.vimrc ]; then
            cecho green "OK:"
            echo " ~/.vimrc -> $FILESROOT/vimrc"
        else
            cecho red "ERROR:"
            echo "Could not create the link ~/.vimrc -> $FILESROOT/vimrc"
        fi
    fi
fi
echo

ensuredir ~/.vim/colors
if [ "$(readlink ~/.vim/colors/$COLORSCHEME_FILE)" == "$FILESROOT/$COLORSCHEME_FILE" ]; then
    cecho green "OK:"
    echo " ~/.vim/colors/$COLORSCHEME_FILE -> $FILESROOT/$COLORSCHEME_FILE"
else
    if [ -f ~/.vim/colors/$COLORSCHEME_FILE ]; then
        cecho yellow "WARNING:"
        echo "$COLORSCHEME_FILE color scheme already installed."
        echo "you can link later using the command"
        cecho white "ln -s \$FILESROOT/$COLORSCHEME_FILE ~/.vim/colors/$COLORSCHEME_FILE\n"
        echo "or running this script again"
    else
        echo "Linking $FILESROOT/$COLORSCHEME_FILE";
        ln -s $FILESROOT/$COLORSCHEME_FILE ~/.vim/colors/$COLORSCHEME_FILE
        if [ -f ~/.vim/colors/$COLORSCHEME_FILE ]; then
            cecho green "OK:"
            echo " ~/.vim/colors/$COLORSCHEME_FILE -> $FILESROOT/$COLORSCHEME_FILE"
        else
            cecho red "ERROR:"
            echo "Could not create the link ~/.vimrc -> $FILESROOT/vimrc"
        fi
    fi
fi
echo

ensuredir ~/.vim/undo;
ensuredir ~/.vim/backup;
ensuredir ~/.vim/swap;

