#!/bin/bash

if [ "$1" == "--help" ]; then
    echo "Usage: wsl-folder [distro name]"
    echo "No params: list all ditributions and their path, separated by |"
    echo "[distro name]: provide the windows-like path where a distro is installed"
    echo "               to get the linux path, use the command ${cYellow}wspath${c0}"
    exit 0
fi

if ! command -v "powershell" &> /dev/null; then
    echo -e "${cYellow}powershell${c0} is not available in the PATH."
    echo "Aborting"
    exit 1
fi

DISTRO_AND_FOLDERS=$(powershell -Command 'foreach ($item in (Get-ChildItem -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Lxss")) { $item.GetValue("DistributionName") + "|" + $item.GetValue("BasePath") }' | grep -i -v "^|" | sed 's/\\\\?\\//' | tr -d '\r' )

if [ -z "$1" ]; then
    echo "${DISTRO_AND_FOLDERS[@]}"
else
    echo "${DISTRO_AND_FOLDERS[@]}" | grep "^$1|" | sed "s/$1|//g"
fi
