#!/bin/bash

PERF=~/.files_profile

# ----------------------------------------------------------------------
# Edit your ~/.bashrc ou /etc/bah.bashrc file, and make it run this file
# if [ -f ~/files/bash.d/run_bash ]; then . ~/files/bash.d/run_bash; fi
# ----------------------------------------------------------------------
if [ ! -z $BASH_SOURCE ]; then
        #using bash 3 or higher
        BASHDFOLDER=$(dirname $BASH_SOURCE)
else
        BASHDFOLDER=$(dirname $0)
fi

if [ -f $PERF ]; then
    echo -n "" > $PERF
fi

source_all_scripts() {
    FOLDER=$1
    if [ -d $FOLDER ]; then
        for i in $FOLDER/*.sh; do
            if [ -r $i ]; then
                if [ -f $PERF ]; then
                    TI=`date +%s%N`
                    . $i
                    TF=`date +%s%N`
                    TOT=`expr \( $TF - $TI \) / 1000000`
                    printf "%05d ${i}\n" "${TOT}" >> $PERF
                else
                    . $i
                fi
            fi
        done
        unset i
    fi
}

source_all_scripts "${BASHDFOLDER}"
if [ -d ~/bash.d ]; then
    source_all_scripts ~/bash.d
fi
unset -f source_all_scripts
