#!/bin/bash
# TODO: calculate the charging rate (mAh/minute) and estimated time to full

LC_ALL=en_US.UTF-8
INTERVAL=5
last_state=""

notify() {
  osascript -e "display notification \"$1\" with title \"Battery Monitor\""
}

while :; do
    
    current=$(ioreg -r -n AppleSmartBattery | awk '/"CurrentCapacity"/ {print $3}')
    max=$(ioreg -r -n AppleSmartBattery | awk '/"MaxCapacity"/ {print $3}')
    is_charging=$(ioreg -r -n AppleSmartBattery | awk -F'= ' '/"IsCharging"/ {print $2}')
    is_connected=$(ioreg -r -n AppleSmartBattery | awk -F'= ' '/"ExternalConnected"/ {print $2}')
    current_ma=$(ioreg -r -n AppleSmartBattery | sed -n 's/.*"LegacyBatteryInfo" = {[^}]*"Amperage"=\([-0-9]*\).*/\1/p')
    current_a=$(echo "scale=2; $current_ma / 1000" | bc)
    percent=$(( 100 * current / max ))

    clear

    echo "🔋 Battery: $percent%"
    echo "$current of $max mAh"

    if [ "$is_connected" = "No" ]; then
        state="disconnected"
        message="🚫 Charger NOT connected"
        printf "${cRed}"
    elif [ "$current" = "$max" ]; then
        state="full"
        message="✅ Fully charged"
        printf "${cGreen}"
    elif [ "$is_charging" = "No" ]; then
        state="not_charging"
        message="⚠️  Connected but NOT charging!" 
        printf "${cYellow}"
    else
        state="charging"
        message="⚡️ Charging ... (${current_a} A)"
        printf "${cCyan}"
    fi
    
    printf "${message}${c0}"
    [ "$state" != "$last_state" ] && notify "${message}"

    last_state="$state"
    read -t $INTERVAL -n 1 -s -r

done
