#!/bin/bash
CMD="caffeinate -dismu"

get_pid() {
    ps ax | grep "${CMD}" | grep -v "grep ${CMD}" | awk '{ print $1; }'
}

PID=$(get_pid)

if [ "${1}" == "-p" ] || [ "${1}" == "--pid" ]; then
    if [ "${PID}" == "" ]; then
        echo ""
    else
        echo "${PID}"
    fi
elif [ "${1}" == "--kill" ] || [ "${1}" == "-k" ]; then
    if [ "${PID}" == "" ]; then
        echo "🫥 Not running"
    else
        echo "💀 Kiling ${PID}"
        kill -9 ${PID}
    fi
elif [ "${1}" == "--help" ]; then
    echo "$( basename $0 ) [OPTIONS]"
    echo "      -k, --kill     Stop the running process (if any)"
    echo "      -p, --pid      Check if it is running and shows PID"
    echo "      no params      Start the service (just shows PID"
    echo "                     if alredy running)"
    echo "      --help         Displays this message"
    echo
else
    if [ "${PID}" == "" ]; then
        $CMD &
        PID=$(get_pid)
        echo "☕️ Started: ${PID}"
    else
        echo "🤩 ${PID}"
    fi
fi


