#!/bin/bash

# CONFIGURATION ######################

APPNAME="tor"

######################################

. installer_base.sh
installer_bootstrap

TORBASEURL="https://www.torproject.org/dist/"
if [ "$(which lynx)" != "" ]; then
	TORFILENAME=$(lynx -nolist -dump $TORBASEURL | grep .tar.gz | grep -v .asc | grep -v alpha.tar | awk '{ print $4_$5" "$3; }' | sort -r | awk '{ print $2; }' | head -1)
elif [ "$(which w3m)" != "" ]; then
	TORFILENAME=$(w3m -dump $TORBASEURL | grep .tar.gz | grep -v .asc | grep -v alpha.tar | awk '{ print $4_$5" "$3; }' | sort -r | awk '{ print $2; }' | head -1)
else
	echo "Yout must have 'w3m' or 'lynx' installed to proceed."
	abort_install
fi
TORNAME=$(sed 's/.tar.gz//g' <<< "$TORFILENAME")

echo ""
echo "DOWNLOADING TOR"
echo

cd $APPFOLDER

mkdir source-$TORNAME
cd source-$TORNAME

wget $TORBASEURL$TORFILENAME

if [ ! -f "$TORFILENAME" ]; then
	echo "Error downloading TOR."
	abort_install
fi

echo ""
echo "EXTRACTING FILES"
echo ""

tar xvzf $TORFILENAME || { echo "Error extracting file. Aborted"; abort_install;}

echo ""
echo "ORGANIZING $APPFOLDER"
echo ""

mv $TORNAME/* .
rm -r $TORNAME
rm $TORFILENAME

echo ""
echo "CONFIGURE && MAKE"
echo ""

./configure && make && link_bin "$APPFOLDER/src/tor/tor" "tor"


