#!/bin/bash

cd ~

if [ ! -d .vim ]; then
	mkdir .vim
	if [ ! -d .vim ]; then
		echo "Can't create ~/.vim";
		exit 1;
	fi
fi

cd ~/.vim

if [ -f tmpnerdtree.zip ]; then
    echo "~/.vim/tmpnerdtree.zip altready exists";
    echo "Remove the file and try again";
    exit 1;
fi

wget -O tmpnerdtree.zip https://github.com/scrooloose/nerdtree/archive/master.zip

if [ ! -f tmpnerdtree.zip ]; then
	echo "Failed to download. Aborting.";
	exit 1;
fi

unzip tmpnerdtree.zip && rm tmpnerdtree.zip && echo "tmpnerdtree unzipped and deleted"

cp -r -i nerdtree-master/* . && rm nerdtree-master

echo

echo "Add the following line to your vimrc file to"
echo "set a shortcut for NERDTree plugin"
echo
echo "nmap <C-b> :NERDTreeToggle<cr>"
echo


