#!/bin/bash

# CONFIGURATION ######################

APPNAME="whatweb"

######################################

. installer_base.sh
installer_bootstrap

git clone https://github.com/urbanadventurer/WhatWeb/ $APPFOLDER

link_bin "$APPFOLDER/whatweb" "whatweb"

echo
printf ${cWhite}"Remember to install the packages "${c0}
printf ${cGreen}"ruby"${c0}
printf ${cWhite}" and "${c0}
printf ${cGreen}"rubygems"${c0}
printf ${cWhite}"."${c0}
echo
echo
