#!/bin/bash

PATH_VIM_USER=~/.vim
PATH_VIM_RESOURCES=${FILESROOT}/resources/vim
FILE_THEME=jay.vim

# Try to create a folder and return 0/1
ensuredir () {
    if [ ! -d $1 ]; then
        mkdir -p $1;
        cecho green "OK:"
        echo " create dir $1"
    else
        cecho green "OK:"
        echo " dir $1 already exists. Skipped."
    fi
    if [ ! -d $1 ]; then
        cecho red "ERROR:" 
        echo " Can´t create $1";
        echo
        return 0;
    fi
    echo
    return 1;
}

echo


if [ "$(readlink ~/.vimrc)" == "$PATH_VIM_RESOURCES/vimrc" ]; then
    cecho green "OK:"
    echo " ~/.vimrc -> $PATH_VIM_RESOURCES/vimrc"
else
    if [ -L ~/.vimrc ]; then
        cecho yellow "WARNING:"
        echo " ~/.vimrc already exists. Unlinking!";
    	unlink ~/.vimrc
    fi
      
    echo "Linking $PATH_VIM_RESOURCES/vimrc";
    ln -s $PATH_VIM_RESOURCES/vimrc ~/.vimrc;
    if [ -L ~/.vimrc ]; then
        cecho green "OK:"
        echo " ~/.vimrc -> $PATH_VIM_RESOURCES/vimrc"
    else
        cecho red "ERROR:"
        echo "Could not create the link ~/.vimrc -> $PATH_VIM_RESOURCES/vimrc"
    fi
fi
echo

ensuredir ~/.vim/colors
if [ "$(readlink ~/.vim/colors/$FILE_THEME)" == "$PATH_VIM_RESOURCES/$FILE_THEME" ]; then
    cecho green "OK:"
    echo " ~/.vim/colors/$FILE_THEME -> $PATH_VIM_RESOURCES/$FILE_THEME"
else
    if [ -L ~/.vim/colors/$FILE_THEME ]; then
        cecho yellow "WARNING:"
        echo "~/.vim/colors/$FILE_THEME already exists. Unlinking!";
    	unlink ~/.vim/colors/$FILE_THEME
    fi

    echo "Linking $PATH_VIM_RESOURCES/$FILE_THEME";
    ln -s $PATH_VIM_RESOURCES/$FILE_THEME ~/.vim/colors/$FILE_THEME
    if [ -L ~/.vim/colors/$FILE_THEME ]; then
        cecho green "OK:"
        echo " ~/.vim/colors/$FILE_THEME -> $PATH_VIM_RESOURCES/$FILE_THEME"
    else
        cecho red "ERROR:"
        echo "Could not create the link ~/.vimrc -> $PATH_VIM_RESOURCES/vimrc"
    fi
fi
echo

ensuredir ~/.vim/undo;
ensuredir ~/.vim/backup;
ensuredir ~/.vim/swap;

