#!/bin/bash

WSL_CONF="/etc/wsl.conf"
WSL_CONF_CONTENTS="[automount]\nenabled = true\noptions = \"metadata,umask=22,fmask=11\""

if [ -f $WSL_CONF ]; then
    echo "The file $WSL_CONF already exists and I am not touching it."
    echo "Edit that file and add the following:"
    echo
    echo -e $WSL_CONF_CONTENTS
    echo
    exit 1
fi

if [ $(id -u) -ne 0 ]; then
    echo "This script requires elevation to write to the file $WSL_CONF"
    echo
    echo "Run it again using sudo"
    echo
    exit 1
fi

echo -e $WSL_CONF_CONTENTS >> $WSL_CONF
